version: '3'

services:
  database:
    build: ./database
    container_name: handson-db
    expose:
      - "3306"
  web_server:
    build: ./server
    container_name: handson-server
    ports:
      - "8081:8080"
    depends_on:
      - database